basic dto, api, repository, crud init
kdh-92/Tiggle pull request #48
Opened 2023-07-11 11:39 UTC by kdh-92

> member, tx, comment, tag, reaction에 해당하는 entity, dto, api, repository & 기본 crud(delete 제외) 생성
- dto, crud 등에 필요한 내용을 추후 논의 예정

2023-07-11 11:40 UTC, kdh-92 commented
현재 member, comment 작업, reaction, tag, transaction 추가 예정

2023-07-11 12:55 UTC, choesw commented on backend/tiggle/src/main/resources/db/schema.sql
왼쪽에 서브 모니터는 실수로 같이 캡쳐됐네요;;

2023-07-11 12:56 UTC, choesw commented on backend/tiggle/src/main/java/com/side/tiggle/domain/transaction/model/TransactionType.java
> +    INCOME, OUTCOME
@kdh-92 REFUND도 있어야 할 것 같습니다!

2023-07-11 12:56 UTC, kdh-92 commented on backend/tiggle/src/main/java/com/side/tiggle/domain/transaction/model/TransactionType.java
> +    INCOME, OUTCOME
넵!

2023-07-11 12:58 UTC, kdh-92 commented on backend/tiggle/src/main/resources/db/schema.sql
SQLDBM을 처음 알고 써보는데 엄청나군요..!?

2023-07-11 13:01 UTC, choesw commented on backend/tiggle/src/main/java/com/side/tiggle/domain/member/api/MemberApiController.java
> +    @Transactional
@kdh-92 Transactional 은 보통 controller 레벨 보다는 service 레벨에서 꼭 필요한 경우에만 사용한다고 알고 있어서, 관련 있는 로직이 들어가는게 아니라면 당장은 빼두는 것 어떨까요?

2023-07-11 13:02 UTC, kdh-92 commented on backend/tiggle/src/main/java/com/side/tiggle/domain/member/api/MemberApiController.java
> +    @Transactional
service에 넣은 줄 알았는데 controller 쪽에 다 넣어뒀네요..!! 수정해두겠습니다 :)

2023-07-11 13:15 UTC, choesw commented on backend/tiggle/src/main/java/com/side/tiggle/domain/comment/api/CommentApiController.java
> +@RequestMapping("/comment")
@kdh-92 개취 입니다만 API 형식을 `/api/v1` 로 통일하는거 어떻게 생각하시나요?
개인적으로는 `/api`를 앞에 붙이는게 나중에 FE 쪽 라우팅 포인트랑 구분이 확실히 되어서 좋더라고요
버전은... 저희가 만약 이 프로젝트를 오래오래 한다면 ㅎㅎ 버전 구분이 필요할 수도 있을 것 같아요... v1은 그냥 `/api` 로만 통일해도 좋구요!

2023-07-11 13:16 UTC, kdh-92 commented on backend/tiggle/src/main/java/com/side/tiggle/domain/comment/api/CommentApiController.java
> +@RequestMapping("/comment")
/api/v1 좋습니다 :)

2023-07-11 13:17 UTC, choesw requested changes
분량 많았을텐데 수고하셨습니다..!! 추가 논의 필요한 부분들은 수요일에 다시 얘기해봐요 :)
수정 요청 드린 부분은 수정해주시면 다시 확인하도록 할게요!

2023-07-12 01:07 UTC, choesw approved these changes

2023-07-12 01:07 UTC, choesw commented on backend/tiggle/src/main/java/com/side/tiggle/domain/comment/service/CommentService.java
> +        return CommentDto.fromEntity(commentRepository.save(comment));
말씀하신 코멘트는 `List<CommentDto>`를 반환하지 않나요? `getAllComment` 에서 사용하신다는 뜻이라면 좋은 것 같습니다!

2023-07-12 01:07 UTC, choesw commented on backend/tiggle/src/main/java/com/side/tiggle/domain/comment/service/CommentService.java
> +        return CommentDto.fromEntity(commentRepository.save(comment));
@kdh-92 다만 지금 생각해보니 getAllComment를 사용할 일이 있을까...? 싶네요. tx에 딸린 comment 만 가져오거나, 경우에 따라 사용자의 comment만 조회하거나 할 테니 전체를 다 조회할 일은 없을 것 같아요.
지금은 기본 CRUD 틀만 작업해주신거니까 부분이니 일단 이대로 두시고 나중에 일 재분배 하고 나서 담당하게 되는 사람이 작업하는 걸로 하시면 어떨까요?

2023-07-12 02:35 UTC, kdh-92 commented on backend/tiggle/src/main/java/com/side/tiggle/domain/comment/service/CommentService.java
> +        return CommentDto.fromEntity(commentRepository.save(comment));
정신이 없었네요..
update이 아닌 getAll 부분이 맞습니다!

기존 getAll 로직처럼 쓰기보단 stream 처리로 코드를 간략하게 하면 어떨까 했던 부분이라 말씀하신대로 추후 담당하는 사람이 작업하면 될 것 같아요 :)

2023-07-12 02:36 UTC, choesw commented on backend/tiggle/src/main/java/com/side/tiggle/domain/comment/service/CommentService.java
> +        return CommentDto.fromEntity(commentRepository.save(comment));
@kdh-92 좋습니다!

2023-07-13 14:43 UTC, merged